# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e17a35a963449a24e293bc234c021e48c78add61ccf7dcbeecf9252c006b231ae37d2b0ada041a349d8e53c11edb6904de2873f6361fbb8f8c397fd39c1970c5

test:
  secret_key_base: fd4e0fabe7fc73d9908cb0bfa792189131150557c5b1d6920c9167eb8ecdd1a67dcf70e759f675ad1947dd4d995c869f28e1271e6544d661e137b00b4db9d361

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
